SET LINESIZE 200;
SET PAGESIZE 100;
SELECT (bursa + 100) / 2 AS "Bursa" FROM studenti WHERE bursa IS NOT NULL;
/*1*/   SELECT nume, prenume, an, data_nastere from studenti;
        SAVE p1.sql REPLACE;
/*2*/ SELECT DISTINCT bursa FROM studenti WHERE bursa IS NOT NULL;
/*3*/   GET p1.sql;
        EDIT; -- SELECT nume AS "Numele", prenume AS "Prenumele", an AS "Anul", data_nastere AS "Data nasterii" from studenti;
        RUN;
/*4*/ SELECT nume || ' ' || prenume || ', ' || an AS "Studenti pe ani de studiu" FROM studenti ORDER BY an;
/*5*/ SELECT nume, prenume, data_nastere FROM studenti WHERE data_nastere BETWEEN '01-JAN-95' AND '10-JUN-97' ORDER BY an DESC;
/*6*/ SELECT nume, prenume, an FROM studenti WHERE TO_CHAR(data_nastere, 'YYYY') = 1995;
/*7*/ SELECT * FROM studenti WHERE bursa IS NULL;
/*8*/ SELECT nume, prenume FROM studenti WHERE bursa IS NOT NULL AND an IN ('2', '3') ORDER BY nume, prenume DESC;
/*9*/ SELECT nume, prenume, bursa * 1.15 AS "Bursa marita" FROM studenti WHERE bursa IS NOT NULL;
/*10*/ SELECT * FROM studenti WHERE nume LIKE 'P%' AND an = 1;
/*11*/ SELECT * FROM studenti WHERE prenume LIKE '%a%a%';
/*12*/ SELECT * FROM studenti WHERE prenume IN ('Alexandru', 'Ioana', 'Marius');
/*13*/ SELECT * FROM studenti WHERE bursa IS NOT NULL AND grupa LIKE 'A%';
/*14*/ SELECT nume, prenume FROM profesori WHERE prenume LIKE '%n %' OR prenume LIKE '%n';