SET LINESIZE 200;
SET PAGESIZE 100;
SELECT table_name FROM user_tables;
/*1*/   CREATE SEQUENCE s INCREMENT BY 1 START WITH 10 MAXVALUE 12;
        INSERT INTO cursuri VALUES(s1.NEXTVAL, &titlu, &an, &semestru, &credite);
        INSERT INTO cursuri VALUES(s1.NEXTVAL, &titlu, &an, &semestru, &credite);
        INSERT INTO cursuri VALUES(s1.NEXTVAL, &titlu, &an, &semestru, &credite);
        DROP SEQUENCE s;
/*2*/   UPDATE studenti SET bursa = 500 WHERE nr_matricol IN (SELECT DISTINCT nr_matricol FROM note WHERE valoare = 10);
        UPDATE studenti s SET bursa = 500 WHERE EXISTS (SELECT '' FROM note n WHERE s.nr_matricol = n.nr_matricol AND n.valoare = 10);
/*3*/ UPDATE studenti s SET bursa = 100 * (SELECT AVG(valoare) FROM note n WHERE s.nr_matricol = n.nr_matricol);
/*4*/ DELETE FROM studenti WHERE nr_matricol NOT IN (SELECT DISTINCT nr_matricol FROM note);
/*5*/   ROLLBACK;
        CREATE TABLE studenti(nume VARCHAR2(10), prenume VARCHAR2(10), bursa NUMBER(6, 2), medie NUMBER(4, 2));
        CREATE TABLE temp_studenti AS (SELECT nume, prenume, bursa, (SELECT AVG(valoare) FROM note n WHERE n.nr_matricol = s.nr_matricol) medie FROM studenti s);
        DROP TABLE temp_studenti PURGE;
/*6*/   ALTER TABLE studenti ADD CONSTRAINT pk_studs PRIMARY KEY (nr_matricol);
        ALTER TABLE studenti DROP CONSTRAINT pk_studs;
        ALTER TABLE profesori ADD CONSTRAINT pk_profs PRIMARY KEY (id_prof);
        ALTER TABLE profesori DROP CONSTRAINT pk_profs;
        ALTER TABLE cursuri ADD CONSTRAINT pk_courses PRIMARY KEY (id_curs);
        ALTER TABLE cursuri DROP CONSTRAINT pk_courses;
/*7*/   ALTER TABLE note ADD CONSTRAINT fk_studs FOREIGN KEY (nr_matricol) REFERENCES studenti(nr_matricol) ON DELETE SET NULL;
        ALTER TABLE note DROP CONSTRAINT fk_studs;
        ALTER TABLE note ADD CONSTRAINT nfk_courses FOREIGN KEY(id_curs) REFERENCES cursuri(id_curs) ON DELETE CASCADE;
        ALTER TABLE note DROP CONSTRAINT nfk_courses;
        ALTER TABLE didactic ADD CONSTRAINT fk_profs FOREIGN KEY (id_prof) REFERENCES profesori(id_prof) ON DELETE SET NULL;
        ALTER TABLE didactic DROP CONSTRAINT fk_profs;
        ALTER TABLE didactic ADD CONSTRAINT dfk_courses FOREIGN KEY(id_curs) REFERENCES cursuri(id_curs) ON DELETE CASCADE;
        ALTER TABLE didactic DROP CONSTRAINT dfk_courses;
/*8*/   ALTER TABLE note ADD CONSTRAINT c UNIQUE (nr_matricol, id_curs);
        ALTER TABLE note DROP CONSTRAINT c;
/*9*/   ALTER TABLE note ADD CONSTRAINT c CHECK (valoare >= 1 AND valoare <= 10);
        ALTER TABLE note DROP CONSTRAINT c;
/*10*/ SAVEPOINT s1;
/*11*/ DELETE profesori;
/*12*/ INSERT INTO profesori VALUES(1, 'Breaban', 'Mihaela', 'Conf');
/*13*/ SAVEPOINT s2;
/*14*/ UPDATE profesori SET nume = 'Varlan', prenume = 'Cosmin' WHERE id_prof = 1;
/*15*/ SELECT * FROM profesori;
/*16*/ ROLLBACK TO SAVEPOINT s2;
/*17*/ SELECT * FROM profesori;
/*18*/ ROLLBACK TO SAVEPOINT s1;
/*19*/ SELECT * FROM profesori;