ALTER TABLE albums ADD COLUMN genre VARCHAR(100) NOT NULL;
DELETE FROM charts WHERE 1 = 1;
DELETE FROM albums WHERE 1 = 1;
DELETE FROM artists WHERE 1 = 1;
ALTER TABLE charts AUTO_INCREMENT = 1;
ALTER TABLE albums AUTO_INCREMENT = 1;
ALTER TABLE artists AUTO_INCREMENT = 1;